#!/bin/sh

RELEASE=/var/www/missloopy/

echo 'Copying Python files..'
cp -u *.py $RELEASE
echo 'Copying Shell files..'
cp -u *.sh $RELEASE
echo 'Copying templates directory..'
cp -ru templates $RELEASE
echo 'Copying static directory..'
cp -ru static $RELEASE
